source 'https://rubygems.org'

group :development, :test do
  gem 'cucumber'
  gem 'database_cleaner'
  gem 'watir'
  gem 'rspec'
  gem 'page-object'
  gem 'rake'
  gem 'xvfb'
  gem 'headless'
  gem 'chromedriver-helper'
end